server:
  port: 80
  context-path: /
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wenda?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates
    cache: false 
  
mybatis:
  config-location: classpath:mybatis-config.xml